# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - ticket
  - deploy

ticket-job:
  stage: ticket
  script:
    - echo "Starting Ticketing...."
    - echo "$CI_COMMIT_SHA"
    - |
      curl -k --data "{\"message\":\"$CI_COMMIT_SHA\", \"id_project\":\"$CI_PROJECT_ID\"}" -H 'Content-Type: application/json' -X POST $HOST_TICKET_API
    - echo "Ticket Submitted."

deploy-job:
  stage: deploy
  script:
    - echo "Setup SSH..."
    - mkdir -p ~/.ssh
    - cat $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 10.5.255.7 >> ~/.ssh/known_hosts
    - ssh-keyscan -H 10.5.255.8 >> ~/.ssh/known_hosts
    - ssh-keyscan -H 10.5.255.9 >> ~/.ssh/known_hosts
    - echo "Starting deployment..."
    - rsync -avz --info=NAME --exclude='.git' --exclude='.env.development' --exclude='.vscode' --exclude='.gitlab-ci.yml' --chown=:developer --chmod=770 -e "ssh" ./ root@10.5.255.7:/var/www/html/$CI_PROJECT_NAME
    - rsync -avz --info=NAME --exclude='.git' --exclude='.env.development' --exclude='.vscode' --exclude='.gitlab-ci.yml' --chown=:developer --chmod=770 -e "ssh" ./ root@10.5.255.8:/var/www/html/$CI_PROJECT_NAME
    - rsync -avz --info=NAME --exclude='.git' --exclude='.env.development' --exclude='.vscode' --exclude='.gitlab-ci.yml' --chown=:developer --chmod=770 -e "ssh" ./ root@10.5.255.9:/var/www/html/$CI_PROJECT_NAME
    - echo "Deployment complete."
  rules:
    - if: '$CI_COMMIT_BRANCH == "production" && $CI_PIPELINE_SOURCE == "push"'
      when: always