<?php 
    $inspection_authority = '';

    if($inspect_auth) {

      $list_inspection_authority = explode(";", $inspect_auth);

      if($list_inspection_authority[0] == 1) {
        $inspection_authority .= 'Hold Point ';
      }

      if($list_inspection_authority[1] == 1) {
        $inspection_authority .= 'Witness ';
      }

      if($list_inspection_authority[2] == 1) {
        $inspection_authority .= 'Monitoring / ';
      }

      if($list_inspection_authority[3] == 1) {
        $inspection_authority .= 'Review ';
      } 

    } else {
      $inspection_authority = '-';
    }
  
  ?>

Dear All,
<br>
<br>
<b>Mr/Ms. <?= $transmitter ?>,</b>
<br>
<br>
Has been Updated <b>Material Verification - Report No <?= $report_no ?></b>
<br>
<strong>Employer Inspection Authority : <?= $inspection_authority ?></strong>
<br>
<br>
The report requires Re-Approval due to changes in its contents.
<br>
Please check History for your reference
<br>
<br>
Please refer to link Address on below :
<br>
<br>
<table>
  <tr>
    <td>Inspection Document</td>
    <td>:</td>
    <td> Link ( <a href="<?= $pdf_link ?>">PDF Print Out</a> )</td>
  </tr>
  <tr>
    <td>Portal Link</td>
    <td>:</td>
    <td> Link ( <a href="<?= getenv('LINK_SERVER') ?>"><?= getenv('LINK_SERVER') ?></a> )</td>
  </tr>
  <tr>
    <td>Internet Browser</td>
    <td>:</td>
    <td> Google Chrome</td>
  </tr>
</table>
<br>


Regards,
<br>
SMOE Portal
<br>
(Auto Reminder System)
<br>
<br>

<b>This email auto generated by system.</b>
<br>
<b>Please do not reply to this email address.</b>
<br>
<b>SMOE-IT Dev-Notif-000040</b>