Dear All,
<br>
<br>
<b>Mr/Ms. <?= $requestor ?>,</b>
<br>
<br>
Has been submitting <b>Material Verification - RFI <?= $submission_id ?></b>
<br>
<br>
Please refer to link Address on below :
<br>
<br>
<table>
  <tr>
    <td>Inspection Document</td>
    <td>:</td>
    <td> Link ( <a href="<?= $pdf_link ?>">PDF Print Out</a> )</td>
  </tr>
  <tr>
    <td>Portal Link</td>
    <td>:</td>
    <td> Link ( <a href="<?= getenv('LINK_SERVER') ?>"><?= getenv('LINK_SERVER') ?></a> )</td>
  </tr>
  <tr>
    <td>Internet Browser</td>
    <td>:</td>
    <td> Google Chrome</td>
  </tr>
</table>
<br>
Regards,
<br>
SMOE Portal
<br>
(Auto Reminder System)
<br>
<br>

<b>This email auto generated by system.</b>
<br>
<b>Please do not reply to this email address.</b>
<br>
<b>SMOE-IT Dev-Notif-000036</b>