<html>

<body>
  <p>Dear Mr/Ms. <?= $requestor ?> </p>

  <p>Mr/Ms. <?= $approval_by ?> has been approved your request for update data Material Verification.</p>
  <p>Please refer to the following link address to update data that you request :</p>
  <p>
  <table>
    <tr>
      <td>Update Pages</td>
      <td>:</td>
      <td><a href="<?= $links_docs ?>" target='_blank'><b>Link</b></a></td>
    </tr>
    <tr>
      <td>Internet Browser</td>
      <td>:</td>
      <td>Google Chrome</td>
    </tr>
  </table>
  </p>

  <p>Regards,<br />SMOE Portal<br>(Auto Reminder System)</p>
  <p><b>This email auto generated by system. <br /> Please do not reply to this email address.</b></p>
</body>

</html>