<?php  
  error_reporting(0);

  $legend_inspection_auth = explode(';', $postmail['legend_inspection_auth']);

  if($postmail['legend_inspection_auth']) {
    $inspection_authority = [];
    if(in_array(1, $postmail['legend_inspection_auth']) OR in_array(1, $legend_inspection_auth)) {
      $inspection_authority[] = 'Hold Point ';
    }

    if(in_array(2, $postmail['legend_inspection_auth']) OR in_array(2, $legend_inspection_auth)) {
      $inspection_authority[] = 'Witness ';
    }

    if(in_array(3, $postmail['legend_inspection_auth']) OR in_array(3, $legend_inspection_auth)) {
      $inspection_authority[] = 'Monitoring ';
    }

    if(in_array(4, $postmail['legend_inspection_auth']) OR in_array(4, $legend_inspection_auth)) {
      $inspection_authority[] = 'Review ';
    } 

  } else {
    $inspection_authority = '-';
  }
?>

Dear All,
<br>
<br>
<b>Mr/Ms. <?= $this->user_cookie[1] ?>,</b>
<br>
<br>
Has been Transmitted <b>Visual - Report No <?= $reno_view ?></b>  Visual Inspection Progress
<br>
<br>
  <b>Employer Inspection Authority : <?= implode('/ ', $inspection_authority) ?></b>
<br>
<br>
The report has been updated as per your Comments.
<br>
Please check History for your reference.
<br>
Please refer to link Address on below :
<br>
<br>
<table>
  <tr>
    <td>Inspection Document</td>
    <td>:</td>
    <td> Link ( <a href="<?= $pdf_link ?>">PDF Print Out</a> )</td>
  </tr>
  <tr>
    <td>Portal Link</td>
    <td>:</td>
    <td> Link ( <a href="<?php echo getenv('LINK_SERVER') ?>"><?php echo getenv('LINK_SERVER') ?></a> )</td>
  </tr>
  <tr>
    <td>Internet Browser</td>
    <td>:</td>
    <td> Google Chrome</td>
  </tr>
</table>
<br>

Regards,
<br>
SMOE Portal
<br>
(Auto Reminder System)
<br>
<br>

<b>This email auto generated by system.</b>
<br>
<b>Please do not reply to this email address.</b>
<br>
    <b>SMOE-IT Dev-Notif-000024</b>