<html>

<body>
  <p>Dear Mr/Ms. <?= $inspector ?>, </p>

  <p> <?= $requestor ?> has been completed update data for PCMS - Visual Inspection which is need your approval to
    closing this update request</p>
  <p>Please refer to the following link address to review new data :</p>
  <p>
  <table>
    <tr>
      <td>Approval Pages</td>
      <td>:</td>
      <td><a href= "<?= $links_docs ?>" target='_blank'><b>Link</b></a></td>
    </tr>
    <tr>
      <td>Internet Browser</td>
      <td>:</td>
      <td>Google Chrome</td>
    </tr>
  </table>
  </p>

  <p>Regards,<br />SMOE Portal<br>(Auto Reminder System)</p>
  <p><b>This email auto generated by system. <br /> Please do not reply to this email address.</b></p>
</body>

</html>