<?php
error_reporting(0);

$link_smoe    = site_url('planning_bnp/transmittal_rfi');
$links_public = getenv('LINK_PCMSV2_OUTSIDE').'/planning_bnp/transmittal_rfi';
?>
<p>Dear All,</p>
Request for Inspection <strong><?= $activity_desc[$bnp['id_activity']]['description_of_activity'] ?></strong> No.<?= $bnp['request_no'] ?> for <?= date('d F Y') ?> At <strong><?= $inspect_location ?></strong> - <?= $project_desc ?>.
<br>

<ul>
  <?php foreach ($irn_desc as $key => $value) : ?>
    <li><strong><?= $value['item_tag_description'] ?></strong></li>
  <?php endforeach; ?>
</ul>

* Paint System <strong><?= $paint_system[$bnp['id_paint_system']]['name'] ?></strong>
<br>
<br>

<table style="border: 1px solid black; padding: 20px">
  <tr>
    <td>Link (SMOE Network)</td>
    <td>:</td>
    <td><a href="<?= $link_smoe ?>" target="_blank">link</a></td>
  </tr>

  <tr>
    <td>Link (Public Network)</td>
    <td>:</td>
    <td><a href="<?= $links_public ?>" target="_blank">link</a></td>
  </tr>

</table>
</p>
<p>Regards,<br />SMOE Portal<br>(Auto Notification System)</p>
<p><b>This email auto generated by system. <br /> Please do not reply to this email address. <br> SMOE-IT Dev-Notif-000031</b></p>