name: Build and Analyze PHP Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest  # Menggunakan ubuntu-latest untuk build PHP

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'  # Ganti dengan versi PHP yang sesuai dengan proyek Anda

      # - name: Install dependencies
      #   run: |
      #     composer install  # Menggunakan Composer untuk menginstal dependensi PHP

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          token: ${{ secrets.SONAR_TOKEN }}  # Gunakan token SonarQube yang sudah diset di GitHub Secrets
